// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCell struct {
	SpreadsheetID string `json:"spreadsheetId"`
	RawValue      string `json:"rawValue"`
	RowIndex      int    `json:"rowIndex"`
	ColumnIndex   int    `json:"columnIndex"`
}

type NewSpreadsheet struct {
	Name        string `json:"name"`
	RowCount    int    `json:"rowCount"`
	ColumnCount int    `json:"columnCount"`
}

type UpdateCell struct {
	RawValue string `json:"rawValue"`
}

type UpdateSpreadsheet struct {
	Name        *string `json:"name,omitempty"`
	RowCount    *int    `json:"rowCount,omitempty"`
	ColumnCount *int    `json:"columnCount,omitempty"`
}
